### ISSUE TITLE
How to get a complete data set after filling？

### ISSUE THREAD

**Issue by Cold-little-hippo** [jsyoon0823/GAIN#11]
After reading the article and reading your code, I feel it is wonderf. But there is a question: How do I use the trained GAN to fill my missing data set? And how can I  exported this dataset be completely ?

**Comment by jsyoon0823** [comment]
As can be seen in the line 53 in main_letter_spam.py, the main function returns the imputed data.
This is the imputed data (fill your missing data set after GAN training).
You can use numpy.savetxt to extract this imputed dataset completely.
