### ISSUE TITLE
Congeniality of gain

### ISSUE THREAD

**Issue by panjj1125** [jsyoon0823/GAIN#12]
Hi, I am really interested in congeniality of gain you mentioned in section 6.5 in your paper. Do you mind sharing the code of this part to me? My email address is panjj1125@outlook.com. Thanks for your time.

**Comment by jsyoon0823** [comment]
As can be seen in the paper, congeniality is defined as the absolute weight differences between imputed data and original data.
I think you can easily implement this using sklearn package as follows.
(1) Train logistic regression (or linear regression) using sklearn package on original data and returns the weights of the trained model.
(2) Train logistic regression (or linear regression) using sklearn package on imputed data and returns the weights of the trained model.
(3) Compute the absolute differences between weights obtained from (1) and (2)
