### ISSUE TITLE
Bug introduced in new version of the code?

### ISSUE THREAD

**Issue by redfungus** [jsyoon0823/GAIN#15]
Greetings!

I noticed that in the newest version of the code, in the training phase only the missing data is given to the gain module. So the X in the gain module is actually the data that is missing according to M. So the loss function can't compare the predictions with the original values.

**Comment by jsyoon0823** [comment]
Yes. It is what I intended to.
Usually, the real data itself includes the missing data. So, it is always impossible to compare with the original values.
As can be seen in the loss function in the original paper, we never compare with the original values. Only compared with the 'observed original values'

**Comment by redfungus** [comment]
Thanks for the fast response.
