### ISSUE TITLE
How to decide Missingness Mechanism

### ISSUE THREAD

**Issue by sevhatdoger** [jsyoon0823/GAIN#18]
Hello Jsyoon,

Your work is really nice and thank you for sharing the codes.
The question I have difficulty in finding the answer is this; How can I choose the missing mechanism?
I want to create a missing mechanism of type MCAR, MAR and MNAR, but I could not find it in the code. Can we identify other missing mechanisms by using the function you wrote to create missing data? Or how did you do this?

Thank you.

**Comment by jsyoon0823** [comment]
In this codebase, I only provide MCAR setting. (See 34-36 lines in data_loader.py).
For MAR and MNAR, you can easily make your codes using the following document (http://proceedings.mlr.press/v80/yoon18a/yoon18a-supp.pdf) - see page 7 and 8.
