### ISSUE TITLE
Differences with the paper

### ISSUE THREAD

**Issue by simoons95** [jsyoon0823/GAIN#19]
Hello!
Thank you for your great paper and this code.

I was wondering why some hyperparameters are different from the ones in the paper.
For example, you use ReLu in the code but Tanh in the paper. Or you choose alpha = 100 in the code by default, but alpha = 0.1, 0.5, 1, 2 or 10 in the paper.
And the hint mechanism is completely different (do the mathematical results still hold?).
What should be followed to reproduce the results of the paper?

**Comment by jsyoon0823** [comment]
Thank you for your interest in our paper.
- The paper is published 2 years ago and I keep improving the codes with various combinations of hyper-parameters.
- I also discovered that modified hints are more convenient on implementation and do not decrease the performance.
