### ISSUE TITLE
Using GAIN in inductive mode

### ISSUE THREAD

**Issue by suparno89** [jsyoon0823/GAIN#20]
Can this package be somehow used in inductive mode i.e. can this be trained on a data and then applied to another dataset (test data) without the need of training it on the test data? Which will be equivalent with the sklearn style of first fit_transform() on the training data and then transform() only on the test data?

**Comment by jsyoon0823** [comment]
Yep. I think you can definitely use it in an inductive mode.
You can modify the current implementations with model saving codes (https://cv-tricks.com/tensorflow-tutorial/save-restore-tensorflow-models-quick-complete-tutorial/).
Then, for another dataset, you can just load the trained data and apply to the new data.
