### ISSUE TITLE
Why not both L_G and L_D relevant to V(D,G)?

### ISSUE THREAD

**Issue by yezhengli-Mr9** [jsyoon0823/GAIN#22]
Why not both L_G (Eq. 18)
<img src="https://render.githubusercontent.com/render/math?math=L_G\doteq\sum \left\{(1-m_i) \log \hat{m}_i \oplus L_M \right\}">
 
 and L_D (Eq. 16)
<img src="https://render.githubusercontent.com/render/math?math=L_D\doteq\sum \left\{m_i \log \hat{m}_i \oplus (1-m_i) \log [1-\hat{m}_i] \right\}">
 
directly relevant to V(D,G) (Eq. 4) 
<img src="https://render.githubusercontent.com/render/math?math=V(D,G)\doteq \sum \left\{M^T \log D(\hat{X},H) \oplus (1-M)^T \log [1-D(\hat{X},H)]\right\}"> ?

L_D is relevant (obviously directly derived from V(D,G)) but L_G is irrelevant.

**Comment by jsyoon0823** [comment]
Thank you for your interest in our paper.

In GAN framework, replacing loss for generator from -L_D to the above L_G is common due to the gradient issue.
Please see this link (https://developers.google.com/machine-learning/gan/loss). Especially on modified minimax loss part.

Thanks!
