### ISSUE TITLE
mixed (categorical and numerical) data

### ISSUE THREAD

**Issue by khanwa** [jsyoon0823/GAIN#26]
How to run GAIN when we have mixed (categorical and numerical) data?

**Comment by jsyoon0823** [comment]
For mixed data, we need to use two output heads: one for continuous and the
other for categorical.
Then, we need to use different activation functions (especially using
softmax on categorical output head).

Hopefully, this can resolve your issue.

**Comment by khanwa** [comment]
Thank you for the answer. Can you provide a demo (if possible)?

**Comment by jsyoon0823** [comment]
Unfortunately, we have not published the demo for this extension of GAIN.
