### ISSUE TITLE
alpha

### ISSUE THREAD

**Issue by MelaUrban** [jsyoon0823/GAIN#28]
Hallo!
In your paper in the Supplementary Materials 3. you wrote you choosed alpha among [0.1, 0.5, 1, 2, 10].
In the code you set a default value of 100 for alpha.
Is this a typo?
Thanks!
Mela

**Comment by jsyoon0823** [comment]
Nope. After writing the paper, we discovered that it would be better to extend the range of alpha for the optimal performance. Thus, we also add alpha = 100.0 as well.
