### ISSUE TITLE
original data

### ISSUE THREAD

**Issue by theuselesscorporation** [jsyoon0823/GAIN#30]
In the paper the original data have missing values and data matrix has got missing values as zero. There is also a random matrix that has available values as zeros and missing values as some gaussian random. The Mask matrix indicates the missing values as 0 and available values as one. However, I am not able to correlate these to the values in data loader. My understaning of data_loader.py is 
data_m -> Mask matrix
but i do not undetstand the other two..
looks like miss_data_x is neither random mtarix or data matrix but contains np.nan in missing values. Please correct me if I am wrong
Also, I am confused if the data_x contains missing values?  In the paper the original data has missing values as 'X' what is X? in data_x is it np.nan?

Please help

**Comment by jsyoon0823** [comment]
Thank you for your interest in this repository.
As can be seen in the data_loader file (https://github.com/jsyoon0823/GAIN/blob/master/data_loader.py),
- data_x: original data without missing values. 
- miss_data_x: data with missing values (which are represented as np.nan)
- data_m: a binary matrix that represents either missing (0) or observed (1).

During GAIN training,
- we first replace nan values in miss_data_x to 0 (https://github.com/jsyoon0823/GAIN/blob/master/gain.py#L68)
- then, we combine miss_data_x with random matrix here (https://github.com/jsyoon0823/GAIN/blob/master/gain.py#L169)
