### ISSUE TITLE
Hint matrix 

### ISSUE THREAD

**Issue by xyzyc** [jsyoon0823/GAIN#35]
In gain.py, line 165-166,
    H_mb_temp = binary_sampler(hint_rate, batch_size, dim)
    H_mb = M_mb * H_mb_temp

To my understanding, H_mb_temp is the binary B matrix in the paper for the minibatch, and M_mb is binary mask matrix for the mini batch.
Then H_mb is binary. 
But H_mb should have some 0.5 in the entries.
Also according to the paper, it seems to be H_mb = M_mb * H_mb_temp + 0.5 * (1-H_mb_temp).
Is there something I don't understand?
Thank you!

**Comment by jsyoon0823** [comment]
Thanks for the comments. Please see the previous issue (https://github.com/jsyoon0823/GAIN/issues/2) that addressed quite similar questions on hint mechanism.
