### ISSUE TITLE
No split training and testing sets？

### ISSUE THREAD

**Issue by JeremyChou28** [jsyoon0823/GAIN#37]
Hello, I see that your code did not split the dataset into training and testing sets. You trained all the data and then tested the entire dataset. Isn't this data leakage?

**Comment by JeremyChou28** [comment]
I have another question, shouldn't we calculate RMSE within the original data range? Why are we calculating values within the normalized range. Looking forward to your reply, thank you.

**Comment by jsyoon0823** [comment]
Thanks for your questions.

For the first issue, please see this link (https://github.com/jsyoon0823/GAIN/issues/14).
For the second issue, yes, you can compute RMSE in the range of original data as well.
- In the paper, to properly compare across the datasets, we use the normalized data. However, it is definitely correct that we can compute RMSE in the original data range.
- One caveat is that if we use the original data range to compute RMSE, if one feature has very large range, it may be dominant for RMSE value.
