### ISSUE TITLE
Training Query

### ISSUE THREAD

**Issue by robynande** [jsyoon0823/GAIN#38]
Hi, 
I've been implementing your code, and its been really simple to work with due to the great structure- thank you!
I have a question about the GAIN_v2.py script, I noticed that you're training the first and third layers of the generator, but all three layers of the discriminator. What was the rationale behind not training this central layer? I couldn't find a reference to it in the paper, but may have missed it. 
Thanks! Robyn

**Comment by jsyoon0823** [comment]
Not sure what you mentioned as GAIN_v2.py.
Please use gain.py as the official file.

In there, all three layers are trained for both generator and discriminator.
