### ISSUE TITLE
about minibatch

### ISSUE THREAD

**Issue by GA17AI** [jsyoon0823/GAIN#39]
Hi, thanks for such innovative ideal open source! However, I have a question: in the code of gain.py, lines 159 to 161, when taking minibatch training, is random, which does not guarantee that all the data is traversed. Why is training not designed to go through all batches in order to complete the training of an epoch？

**Comment by jsyoon0823** [comment]
That is just for implementation simplicity. No other reasons.
You can easily change it as epoch training that guarantees to utilize all samples.
Thanks!
