### ISSUE TITLE
Unecessarily repeated Z sampling

### ISSUE THREAD

**Issue by guilhermelawless** [jsyoon0823/GAIN#5]
In these 2 lines New_X_mb is computed using random noise Z, then is sent to Generator and Discriminator as Z again, so they are used to re-sample.

I don't think there's an issue except for unecessary re-sampling of Z, because the values will all get substituted.

https://github.com/jsyoon0823/GAIN/blob/1996ed9cae3803fbe8c5cb7cbba0789e2ae1c395/MNST_Code_Example.py#L194

https://github.com/jsyoon0823/GAIN/blob/1996ed9cae3803fbe8c5cb7cbba0789e2ae1c395/MNST_Code_Example.py#L208

**Comment by jsyoon0823** [comment]
Agreed.
