### ISSUE TITLE
Why G_loss doesn’t converge much?

### ISSUE THREAD

**Issue by cococ0j** [jsyoon0823/GAIN#9]
Hi Jinsung,

Thank you for your fabulous paper. I got some inspirations in gapfilling satellite image time series from your model.

Just have one question. When I implement your model and tried to train on my own data, which is 1000 by 1000 pixel images with 78 bands, I just find the G_loss didn't converge very much. Usually, it is around 13 to 14, which is, in my experience, quite a large number. Have you met this situation when you developed your model?

Cheers,
Steve

**Comment by jsyoon0823** [comment]
I think this is because the dimensions of the dataset are too high (1 million).
With very high-dimensional data and small number of data, it is hard for the generator to learn the meaningful patterns.
